### ISSUE TITLE
-trait all not working

### ISSUE THREAD

**Issue by philipbg** [grimmlab/permGWAS#10]
In documentation:

It is possible to run permGWAS2 for several phenotypes located in the same phenotype file one after another. You can either specify a list of phenotypes or run permGWAS2 for all available phenotypes in the file by using the key word all' with this example

`python3 permGWAS.py -x PATH_TO_GENOTYPE -y PATH_TO_PHENOTYPE -trait all`

However, when trying to use -trait all, the following error message appears:

`Phenotype all is not in phenotype file`

**Comment by MauraJohn** [comment]
Thanks for letting us know. It should work now.

**Comment by philipbg** [comment]
Thanks, that's working now
