### ISSUE TITLE
Sample ids of covariates and phenotype do not match.

### ISSUE THREAD

**Issue by rcarleial** [grimmlab/permGWAS#7]
Hi. I am trying to run your software on my dataset. My genotype data is a binary plink file. Without any covariate, the software runs just fine. As soon as I add covariates, I get the title error message. I have checked extensively for any mismatch between the cov and pheno files, and found none. I even used R to arrange the IDs so they appear in the same order in both files, but this has not changed anything. I tried to convert the plink file to H5 (in case the double ID columns were causing the issue) but it didn't work. I do not know what else I can do. I am copying the head of both files down below. Any help would be appreciated. I will use the opportunity to ask how should I code missing data (empty, NAs, etc)? Also, if my phenotype is binary, how it should be coded? Plink asks for 2 for cases and 1 for controls. Does your software accepts that? 

PHENO:
FID,aod_FR
10E1,1
10E3,1
10E4,1
10E6,1
10N1,1
10N3,1
10N3b,1
10S1,1
10S6,1

COV:
FID,RainfallAve_1km_91to20,Elevation_1haAve,Ca_Mg,SO2_SO4_1,NO2_NO3__1,DDEG,DBH
10E1,761.0971351,86.05000114,4.5,2.5,9.2,378.7459472,78.7
10E3,761.0971351,86.05000114,4.5,2.5,9.2,378.7459472,49.8
10E4,761.0971351,86.05000114,4.5,2.5,9.2,378.7459472,52.1
10E6,761.0971351,86.05000114,4.5,2.5,9.2,378.7459472,68.1
10N1,761.0971351,86.05000114,4.5,2.5,9.2,378.7459472,71
10N3,761.0971351,86.05000114,4.5,2.5,9.2,378.7459472,59
10N3b,761.0971351,86.05000114,4.5,2.5,9.2,378.7459472,59
10S1,761.0971351,86.05000114,4.5,2.5,9.2,378.7459472,88.8
10S6,761.0971351,86.05000114,4.5,2.5,9.2,378.7459472,65

**Comment by MauraJohn** [comment]
Hi rcarleial, 
Unfortunately, I was not able to recreate your error with my own data. Could you maybe send me some sample data via email (maura.john@tum.de)? Then I can try and find the issue. 
Regarding your second question: 
Missing data should either be empty or coded as np.nan.
Regarding your third question:
Yes, permGWAS should accept binary data coded as 1 and 2.
