### ISSUE TITLE
could not convert string to float:'1\t13894\t0|t13894'

### ISSUE THREAD

**Issue by myswords98** [grimmlab/permGWAS#9]
I use : python3 permGWAS.py -x  ./data/mydata.map  -y ./data/mypheno.pheno
The following error occurred：
Failure when running permGWAS2.0
could not convert string to float:'1\t13894\t0|t13894'

mypheno.pheno file is
FID IID phenotype_value
11797 11797 0.96590
9936 9936 0.83560

**Comment by MauraJohn** [comment]
Hi,
Given the error message, I think your map file is tab delimited and contains a typo (|t instead of \t). However, permGWAS needs the entries in the map file to be separated by a single white space. 
I hope this helps.
